server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
# MariaDB configuration.
spring.datasource.url = jdbc:mariadb://172.17.0.1:3306/procrecdb
spring.datasource.username = usrdev
spring.datasource.password = p455w0rD
spring.jpa.hibernate.ddl-auto = update
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,org.vaadin.example
spring.jpa.defer-datasource-initialization = never
spring.sql.init.mode = never
#server.servlet.session.timeout=400m
vaadin.push.heartbeat-interval=30
vaadin.push.connection.timeout=30

spring.mail.host=webmail.rionegro.gub.uy
spring.mail.port=587
spring.mail.username=recibos.liquidaciones@rionegro.gub.uy
spring.mail.password=Pass1234X
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=webmail.rionegro.gub.uy

mail.imap.host=webmail.rionegro.gub.uy
mail.imap.ssl.trust=webmail.rionegro.gub.uy
mail.imap.ssl.checkserveridentity=false
mail.imap.port=993
mail.imap.user=recibos.liquidaciones@rionegro.gub.uy
mail.imap.password=Pass1234X
mail.imap.folder=INBOX


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Para Vaadin (si usas Spring Boot 2.x)
vaadin.servlet.url-mapping=/vaadin/*

whatsapp.server.url=http://localhost:3000
spring.application.name=WhatsAppRecibosAPI

app.public.url.whatsapp=http://10.10.104.238:8080
app.public.url.telegram=http://10.10.104.238:8080